---
functional:
  - Пользователь должен иметь возможность зарегистрироваться через email или социальные сети (GitHub, Discord).
  - Пользователь должен иметь возможность восстановить пароль через email
  - Пользователь должен иметь возможность создавать батл с указанием уровня сложности, выбора языка программирования,выбор соперника (случайный пользователь, друг, бот), указание времени на выполнение
  - Пользователь видит редактор кода соперника
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Пользователь может просмотреть завершенные игры
  - Пользователи должны иметь возможность присоединяться к существующим баттлам
  - Пользователи должны иметь возможность запускать и тестировать свой код в реальном времени  
  - Система должна проверять код на соответствие условиям задачи и возвращать результат (успех/ошибка)
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт реализован на двух языках (английский, русский)
implicit:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Система должна поддерживать одновременное участие большого количества пользователей в баттлах без потери производительности
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
